FROM pritunl/archlinux
MAINTAINER patrickpfrey@yahoo.com

RUN pacman -S --noconfirm base-devel git wget rsync tar zip unzip cmake boost boost-libs snappy leveldb gperftools ragel tre lapacke blas php python clang


