FROM archlinux:latest
MAINTAINER patrickpfrey@yahoo.com

RUN pacman -Sy --noconfirm base-devel gcc git nettle wget rsync tar zip unzip cmake boost boost-libs snappy leveldb gperftools ragel tre lapacke blas php python clang
