FROM base/archlinux:latest
MAINTAINER patrickpfrey@yahoo.com

RUN pacman -S --noconfirm base-devel gcc git wget rsync tar zip unzip cmake boost boost-libs snappy leveldb gperftools ragel tre lapacke blas php python clang


